#!/usr/bin/env bash

[[ $TRACE ]] && set -x
set -e

if [[ $# -lt 1 ]]; then
  echo "I'm supposed to do what now?"
  exit 1
fi

# If the last argument starts with a . use it otherwise just use .
jq_opts='.'
if [[ "${!#:0:1}" == '.' ]]; then
  jq_opts="${!#}"
fi

curl -s "$@" | jq "$jq_opts"
