#!/usr/bin/env bash
#
# Lazy way to output new AWS credentials e.g.:
#
# $ ./output-aws-credentials ~/Downloads/credentials.csv
# Username:             sysadmin
# Access Key ID:        ACETIV82S2QJ1UKJP8DV
# Secret Access Key ID: EzhArEibCDkF910vq7tlmPpgRukZk8KJuSM+2u2o
#


creds_file="$1"

if [[ ! -f $creds_file ]]; then
  echo 'Where is the credentials.csv?'
  exit 1
fi

awk -F, 'NR==2 {gsub(/"/, "", $1); print "Username:             " $1 "\nAccess Key ID:        " $2 "\nSecret Access Key ID: " $3}' \
  $creds_file
