#!/bin/sh
#
# Author:
#   z0mbix
# Description:
#   Utility to easily locate OpenBSD packages for the current release
# Requirements:
#   An OpenBSD system
# Notes:
#   Package index file (index.txt) format changed from 4.6 onwards
#

version=$(uname -r | cut -d '.' -f 1,2)
release=$(uname -r)
arch=$(uname -m)
pkgfile="$HOME/.packages-$release"
ftpmirror=ftp.openbsd.org
ftppath=pub/OpenBSD/$release/packages/$arch
indexfile=index.txt

if [ $# -lt 1 ]; then
  echo "Please specify atleast one package to search for."
else
  if [ ! -f $pkgfile ]; then
    echo "$pkgfile does not exist, downloading..."
    ftp -4 -V -o - ftp://$ftpmirror/$ftppath/$indexfile | awk '{print $10}' > $pkgfile

    if [ ! -f $pkgfile ]; then
      echo "Please manually download the file:"
      echo "$ftpmirror/$ftppath/$indexfile"
      echo "and save it as:"
      echo "$pkgfile"
      exit
    fi
  fi
  for pkg in $@; do
    echo "Results for: $pkg"
    grep -i "^$pkg" $pkgfile
    echo
  done
fi
