#!/usr//bin/env bash
#
# Basic elasticsearch snapshot clean up script
#

snapshots_to_keep='8'
snapshot_repo=$1
es_host='127.0.0.1'
es_port='9200'

which jq 1>/dev/null || exit 1

if [[ -z $snapshot_repo ]]; then
  echo 'You need to specify a snapshot repository!'
  echo 'The following repos are available:'
  curl -s "${es_host}:${es_port}/_snapshot/_all" | jq '.|keys'[]
  exit 1
fi

snapshots=$(curl -s "${es_host}:${es_port}/_snapshot/${snapshot_repo}/_all?pretty" |\
              jq -r '.snapshots[].snapshot + " " + .end_time' |\
              sort -k 2 -r |\
              tail -n+${snapshots_to_keep})

delete_snapshot() {
  local ss=$1
  echo "Deleting snapshot: $ss"
  curl -s -X DELETE "${es_host}:${es_port}/_snapshot/${snapshot_repo}/${ss}"
}

for snapshot in ${snapshots[@]}; do
  delete_snapshot $snapshot
done
